# Generated by Django 4.2 on 2024-12-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdmin',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
            ],
            bases=('product.product',),
        ),
    ]
