# Generated by Django 4.2 on 2024-12-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAdmin',
        ),
    ]
