# Generated by Django 4.2 on 2024-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_is_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AddField(
            model_name='product',
            name='immg',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
