# Generated by Django 4.2 on 2024-12-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_immg_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='pictur',
        ),
    ]
