# Generated by Django 4.2 on 2024-12-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pictur',
            new_name='imag',
        ),
    ]
