# Generated by Django 4.2 on 2024-12-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_pictur_product_imag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
