# Generated by Django 4.2 on 2024-12-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_city_code_remove_city_provence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='provence',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
