# Generated by Django 4.2 on 2024-12-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_city_create_provence_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='provence',
            old_name='create',
            new_name='created',
        ),
    ]
