# Generated by Django 4.2 on 2024-12-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_create_city_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='provence',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='provence',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
